source("1_data_integration.R", echo=TRUE)
source("2_calculations_EF_BA_TPA.R", echo = TRUE)
source("3_summarize_data.R", echo=TRUE)
source("4_calculations_biomass.R", echo=TRUE)
source("5_calculations_sps_dom_rich.R", echo=TRUE)
source("6_final_summary.R", echo=TRUE)